services:
  traefik:
    container_name: traefik
    hostname: traefik
    restart: always
    build:
      context: ./traefik
    ports:
      - "80:80"
      # TLS を使う場合は 443 も開ける
      # - "443:443"
      # ダッシュボードは traefik.localhost 経由で出すので 8080 は基本不要
      # - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik_data/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - web
    labels:
      - "traefik.enable=true"
      # Traefik dashboard を http://traefik.localhost で公開
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"

  portainer:
    container_name: portainer
    hostname: portainer
    restart: always
    build:
      context: ./portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/portainer_data:/data
    networks:
      - web
    labels:
      - "traefik.enable=true"
      # Portainer 本体を http://portainer.localhost で公開
      - "traefik.http.routers.portainer.rule=Host(`portainer.localhost`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  web:
    driver: bridge
